theme: jekyll-theme-cayman
title: [Bridging Innovation: Translational Medical Robotics Research]
description: [Full day workshop | IEEE International Conference on Robotics and Automation (ICRA 2025) Atlanta]
